"""small model updates

Revision ID: 598955801650
Revises: 07623369ed48
Create Date: 2020-07-18 22:40:58.441362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598955801650'
down_revision = '07623369ed48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
