"""baseline

Revision ID: a6517a911ce8
Revises: f6e3d9e8f46d
Create Date: 2020-07-17 23:26:48.548911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6517a911ce8'
down_revision = 'f6e3d9e8f46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
